apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: alertmanager-bot-pv
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  claimRef:
    namespace: monitoring
    name: alertmanager-bot-pvc
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: alertmanager-bot
  name: alertmanager-bot-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: alertmanager-bot-pv
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
items:
  - apiVersion: v1
    data:
      # echo -n '-456598003' | base64
      # echo -n '864218369:AAELCFsOI-GFVZvph0_JN8ZCPnLzyC2hb3w' | base64
      admin: LTQ1NjU5ODAwMw==
      token: ODY0MjE4MzY5OkFBRUxDRnNPSS1HRlZadnBoMF9KTjhaQ1BuTHp5QzJoYjN3
    kind: Secret
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager-bot
      name: alertmanager-bot
      namespace: monitoring
    type: Opaque
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager-bot
      name: alertmanager-bot
      namespace: monitoring
    spec:
      ports:
        - name: http
          port: 8080
          targetPort: 8080
      selector:
        app.kubernetes.io/name: alertmanager-bot
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager-bot
      name: alertmanager-bot
      namespace: monitoring
    spec:
      #podManagementPolicy: OrderedReady
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: alertmanager-bot
      #serviceName: alertmanager-bot
      template:
        metadata:
          labels:
            app.kubernetes.io/name: alertmanager-bot
          name: alertmanager-bot
          namespace: monitoring
        spec:
          containers:
            - args:
                - --alertmanager.url=http://localhost:9093
                - --log.level=info
                - --store=bolt
                - --bolt.path=/data/bot.db
              env:
                - name: TELEGRAM_ADMIN
                  valueFrom:
                    secretKeyRef:
                      key: admin
                      name: alertmanager-bot
                - name: TELEGRAM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: token
                      name: alertmanager-bot
              image: metalmatze/alertmanager-bot:0.4.2
              imagePullPolicy: IfNotPresent
              name: alertmanager-bot
              ports:
                - containerPort: 8080
                  name: http
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 25m
                  memory: 64Mi
              volumeMounts:
                - mountPath: /data
                  name: alertmanager-bot-pvc
          restartPolicy: Always
          volumes:
            - name: alertmanager-bot-pvc
              persistentVolumeClaim:
                claimName: alertmanager-bot-pvc
#      volumeClaimTemplates:
#        - apiVersion: v1
#          kind: PersistentVolumeClaim
#          metadata:
#            labels:
#              app.kubernetes.io/name: alertmanager-bot
#            name: alertmanager-bot-pvc
#            namespace: monitoring
#          spec:
#            accessModes:
#              - ReadWriteOnce
#            resources:
#              requests:
#                storage: 1Gi
#            storageClassName: standard
kind: List