apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: eng-telegram-bot-pv
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  claimRef:
    namespace: monitoring
    name: eng-telegram-bot-pvc
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eng-telegram-bot-pvc
  namespace: monitoring
  #volume.beta.kubernetes.io/storage-class:
  labels:
    app: eng-telegram-bot
spec:
  # storageClassName: <BACKEND_SC_NAME>
  accessModes:
    - ReadWriteOnce
  volumeName: eng-telegram-bot-pv
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eng-telegram-bot-tmpl
  namespace: monitoring
  #volume.beta.kubernetes.io/storage-class:
  labels:
    app: eng-telegram-bot
spec:
  # storageClassName: <BACKEND_SC_NAME>
  accessModes:
    - ReadWriteOnce
  volumeName: eng-telegram-bot-pv
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi