#apiVersion: storage.k8s.io/v1beta1
#kind: StorageClass
#metadata:
#  name: fast
#  namespace: monitoring
#provisioner: kubernetes.io/gce-pd
#parameters:
#  type: pd-ssd
#allowVolumeExpansion: true
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: data-volume-1
  namespace: monitoring
spec:
  capacity:
    storage: 250Gi
  claimRef:
    namespace: monitoring
    name: prometheus-claim
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/prometheus
  #persistentVolumeReclaimPolicy: Retain
  #storageClassName: fast
  #gcePersistentDisk:
    #fsType: ext4
  #  pdName: prometheus-volume
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-claim
  namespace: monitoring
  #annotations:
  #  volume.beta.kubernetes.io/storage-class: "fast"
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: data-volume-1
  volumeMode: Filesystem
  resources:
    requests:
      storage: 250Gi
